### ISSUE TITLE
Option to select search machine

### ISSUE THREAD

**Issue by KeizerDev** [Vogeltak/startpage#2]
Would be awesome to use Google..!

**Comment by Vogeltak** [comment]
You can easily use [DDG bangs](https://duckduckgo.com/bang) to do a lot of things very quickly. e.g. pass your search query to Google: `!g cats` or to Youtube: `!yt cats`.

**Comment by KeizerDev** [comment]
Cool! Didn't know that, may I just switch to DDG!

**Comment by Vogeltak** [comment]
You should definitely switch to DDG!
